[build-system]
requires = ["hatchling", "hatch-polylith-bricks"]
build-backend = "hatchling.build"

[project]
name = "my_example_project"
version = "0.1.0"



requires-python = ">=3.13"

dependencies = []

[tool.hatch.build.hooks.polylith-bricks]

[tool.polylith.bricks]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
